#ifndef OOP_11_02_LIBRARY_GLOBAL_H
#define OOP_11_02_LIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OOP_11_02_LIBRARY_LIBRARY)
#  define OOP_11_02_LIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OOP_11_02_LIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OOP_11_02_LIBRARY_GLOBAL_H
